### ISSUE TITLE
Andrew pushed rather than PR'd.

### ISSUE THREAD

**Issue by jhenshaw** [jhenshaw/quantumhwpm#1]
Andrew pushed his changes directly to master, rather than creating a pull request per the instructions. That's no terrible as it got the same end result, but shows a lack of attention to detail.

The penalty for that will be to resolve an issue. Issues weren't part of the homework, but will be faulted in in this case.

**Comment by awol-msft** [comment]
Now I did so good.  Created a new branch and pull request, should be visible in Pull Requests above.  When can I mark this as closed?!

**Comment by jhenshaw** [comment]
You did magestically.
